services:
    refarwan-web-redis:
        restart: "no"

    refarwan-web-svelte:
        restart: "no"
        image: refarwan-web-svelte:local
        build:
            context: .
            dockerfile: Dockerfile
