name: CI

on:
    pull_request:
        branches: ["main", "staging"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - run: bun install --frozen-lockfile

            - name: Run Linter
              run: bun run lint

            - name: Type check
              run: bun run check

            - name: Run Builder
              run: bun run build
